package com.example.shoppinglist

data class ShoppingItem(
    val id: String,           // Unique identifier for the item (generated by Firebase)
    val name: String,         // Name of the shopping item
    val quantity: Int,        // Quantity of the item
    var isChecked: Boolean    // Indicates whether the item is checked/completed
) {
    // Default constructor for Firebase deserialization
    constructor() : this("", "", 0, false)
}
